name: Attach binary to release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  attach:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: carthage build --archive

    - name: Get
      id: get
      uses: bruceadams/get-release@v1.2.0

    - name: Upload
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get.outputs.upload_url }}
        asset_path: ./WaveSlider.framework.zip
        asset_name: WaveSlider.framework.zip
        asset_content_type: application/zip
